@startuml

!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <u>x</u>
hide methods
hide stereotypes

table(users) {
    primary_key(id): INT
    integration_id: INT
    username: VARCHAR
    name: VARCHAR
    email: VARCHAR
    zip_code: VARCHAR
    ext_id: VARCHAR
    created_on: TIMESTAMP
    last_updated_on: TIMESTAMP
}

table(posts) {
    id: INT
    integration_id: INT
    user_integration_id: INT
    title: VARCHAR
    body: LONGVARCHAR
    user_id: INT
    ext_id: VARCHAR
    created_on: TIMESTAMP
    last_updated_on: TIMESTAMP
}

users "1" -right- "*" posts : user_id

@enduml